export default {
    
    home : '/',
    login : '/login',
    about : '/about-us',
    terms : '/terms-and-conditions',
    faqs : '/faqs',
    privacy : '/privacy-and-policy',
    pr1 : '/password-recovery/verify',
    pr2 :  '/password-recovery/verify/code',
    pr3 : '/password-recovery/new-password',
    account : '/account',
    editAccount : 'edit',
    passwordChange : 'password/change',
    hostEvents : '/host-events',
    hostEventsForm : ':id',
    hostEventsPay : '/host-events/:id/pay',
    hostEventSendInvite : '/host-events/:id/:eventId/invite',
    signup : '/signup',
    events : {
        index : '/events',
        editRoom : ':id/room/edit',        
    },
    inviteesList : '/invitees',
    createInviteeList : '/invitees/create',
    editInviteeList : '/invitees/:id/edit',
    savedCards : '/cards',
    categoriesList : '/categories',
    categoryDetail : '/categories/:id',
    subCategories : '/categories/:id',
    myEvents : '/my-events',
    invitedEvents : '/invited-events',
    eventDetail : '/events/:id',
    editEvent : '/events/:id/edit',
    attendEvent : '/events/:id/attend',
    subscriptions : '/subscription-plan',
    subscriptionPayment : '/subscription-plan/:plan',
    mySubscriptions : '/my-subscriptions',
    uploadStories : '/upload-stories',
    // stories : '/stories',
    myStories : '/my-stories',
    stories : {
        index : '/stories',
        category : ':category',
        listing : ':category/:type',
        detail : ':category/:type/:id',
    },
    shop : {
        index : '/shop',
        products : 'products',
        productDetail : 'products/:id',
    },
    cart : '/cart',
    checkout : '/checkout',
    orders : {
        index : '/orders',
        show : ':order_id',
    },
    event : {
        index : '',
    },
    wishlist : 'wishlists',
    reviews : 'my-reviews',
    contact : '/contact-us'
};